version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run: 
          name: install gbs
          command: |
            sudo sh -c "echo \"deb [trusted=yes] http://download.tizen.org/tools/latest-release/Ubuntu_14.04/ /\" >> /etc/apt/sources.list.d/tizen.list"
            sudo apt-get update
            sudo apt-get install gbs
            sudo apt-get install openjdk-8-jdk
      - run: 
          name: gbs build
          command: |
            gbs -c .gbs.conf build -A armv7l --clean
